name = input("Hi! What is your name? ")
print(f"Hi {name} nice to meat you! My name is Natalie!")
food = input ("What is your favorite food? ")
print(f"Oh my  gosh! {food} is also my favorite food!")
sport = input("What's your favorite sport? ")
print (f"That's so cool, I have played {sport} a few times!")
years = input ("How many years have you been playing for? ")
print(f"Wow! {years} is a long time, you must be really good!")
play = input ("Where do you play? ")
print (f"Oh, cool! Maybe I could come watch you at {play} sometime! (: ")
input (f"Would you like to hear a joke about {sport}?") 
input ("Ok! Why was the stadium so hot after the game?")
input ("")
print ("Because all the fans left! Clever, I know! ")
time = input ("What time is it?")
print (f"{time}!! I have to run, but it was so nice to meet you {name}, lets play {sport} and eat {food} together soon!")