print("                       ___                                                   ")
print (  "                      (   )                                               ")
print ("___  ___  ___   .--.     | |   .--.      .--.    ___ .-. .-.     .--.       ")
print ("(   )(   )(   ) /    \   | |   /    \    /    \  (   )   '   \   /    \     ")
print (" | |  | |  | | |  .-. ;  | |  |  .-. ;  |  .-. ;  |  .-.  .-. ; |  .-. ;    ") 
print (" | |  | |  | | |  | | |  | |  |  |(___) | |  | |  | |  | |  | | |  | | |    ")
print (" | |  | |  | | |  |/  |  | |  |  |      | |  | |  | |  | |  | | |  |/  |    ")
print (" | |  | |  | | |  ' _.'  | |  |  | ___  | |  | |  | |  | |  | | |  ' _.'    ")
print (" | |  ; '  | | |  .'.-.  | |  |  '(   ) | '  | |  | |  | |  | | |  .'.-.    ")
print ( "' `-'   `-' ' '  `-' /  | |  '  `-' |  '  `-' /  | |  | |  | | '  `-' /    ")
print ( " '.__.'.__.'   `.__.'  (___)  `.__,'    `.__.'  (___)(___)(___) `.__.'     ")
print ("                                                                            ")                                                                                          
name = input("Hi! What is your name? ")
print(f"Hi {name} nice to meat you! My name is Natalie!")
food = input ("What is your favorite food? ")
print(f"Oh my  gosh! {food} is also my favorite food!")
sport = input("What's your favorite sport? ")
print (f"That's so cool, I have played {sport} a few times!")
years = input ("How many years have you been playing for? ")
print(f"Wow! {years} is a long time, you must be really good!")
play = input (f"Where do you play {sport} at? ")
print (f"Oh, cool! Maybe I could come watch you at {play} sometime! (: ")
place = input ("What is your favorite place you have ever traveled? ")
print (f"That is so cool! {place} must have been so fun!")
thing = input (f"What is your favorite thing to do in {place}?")
print ("Sounds amazing!")
genre = input ("What genre of music do you listen to? ")
input (f"Nice! Whats your favorite {genre} singer or band? ")
print ("That's cool!")
time = input ("What time is it? ")
print (f"{time}! Darn, I have to leave in two minutes, but before I go, I wanted to tell you a joke about {sport} ") 
input ("Why was the stadium so hot after the game? ")
input ("")
print ("Because all the fans left!")
input ("")
print (f"I have to run, but it was so nice to meet you {name}, we should play {sport} and eat {food} together soon!")   
input ("")                           
print (".______   ____    ____  _______  __  ")
print ("|   _  \  \   \  /   / |   ____||  |  ")
print ("|  |_)  |  \   \/   /  |  |__   |  |  ")
print ("|   _  <    \_    _/   |   __|  |  |  ")
print ("|  |_)  |     |  |     |  |____ |__|  ")
print ("|______/      |__|     |_______||__|  ")